const users = require('./user');
const subscriptions = require('./subscription')
const movie = require('./movie')
const genre = require('./genre')
const episode = require('./episode')
const actors = require('./actor')
const comments = require('./comment')
const ratings = require('./rating')
const favourites = require('./favourite')
module.exports = {users, subscriptions, movie, genre, episode, actors, comments, ratings, favourites}